stages:
  prepare:
    cmd: python src/prepare.py data/data.xml
    deps:
    - src/prepare.py
    - data/data.xml
    params:
    - prepare.seed
    - prepare.split
    outs:
    - data/prepared
  featurize:
    cmd: python src/featurization.py data/prepared data/features
    deps:
    - data/prepared
    - src/featurization.py
    params:
    - featurize.max_features
    - featurize.ngrams
    outs:
    - data/features
  train:
    cmd: python src/train.py data/features model.pkl
    deps:
    - data/features
    - src/train.py
    params:
    - train.min_split
    - train.n_est
    - train.seed
    outs:
    - model.pkl
  evaluate:
    cmd: python src/evaluate.py model.pkl data/features
    deps:
    - data/features
    - model.pkl
    - src/evaluate.py
    metrics:
    - eval/metrics.json
    plots:
    - evaluation/plots/confusion_matrix.json:
        cache: false
        template: confusion
        x: actual
        y: predicted
    - evaluation/plots/precision_recall.json:
        cache: false
        x: recall
        y: precision
    - evaluation/plots/roc.json:
        cache: false
        x: fpr
        y: tpr
    - eval/importance.png
params:
- dvclive/params.yaml
metrics:
- dvclive/metrics.json
plots:
- dvclive/plots/sklearn/train/confusion_matrix.json:
    template: confusion
    x: actual
    y: predicted
    title: Train Confusion Matrix
    x_label: True Label
    y_label: Predicted Label
- dvclive/plots/sklearn/test/confusion_matrix.json:
    template: confusion
    x: actual
    y: predicted
    title: Test Confusion Matrix
    x_label: True Label
    y_label: Predicted Label
